name: Continuous Integration

on: push

jobs:
  chromatic-deployment:
    name: Deploy to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish to Chromatic
        id: publish
        if: github.ref != 'refs/heads/master'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
      - name: Publish to Chromatic and auto accept changes
        if: github.ref == 'refs/heads/master'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
      - name: Run Storybook tests
        run: yarn test-storybook --coverage
        if: steps.publish.outputs.storybookUrl
        env:
          TARGET_URL: ${{ steps.publish.outputs.storybookUrl }}
