name: Tests

on: push

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Storybook Tests
        run: yarn test-storybook:ci
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
